#Deriving the latest base image
FROM python:latest


#Labels as key value pair
LABEL Maintainer="Loose.Goose"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /usr/app/src

#to COPY the remote file at working directory in container
COPY agent_main.py ./
COPY agent.py ./

#Add requirements
#ADD ./requirements.txt ./
#RUN python3 -m pip install -r requirements.txt
# Now the structure looks like this '/usr/app/src/test.py'
# Expose the agent listener port
EXPOSE 8574
RUN apt-get update
RUN apt-get install -y iputils-ping
#CMD instruction should be used to run the software
#contained by your image, along with any arguments.
CMD [ "python", "-u", "./agent_main.py"]

#docker image build -t agent:0.0.1 "X:\Python Projects\Community\Achilles\Achilles\agent"